### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by ghost** [dwyl/CRM#1]
Moved from https://github.com/dwyl/hq/issues/161

> Make or Buy Decision: https://youtu.be/vxZSaDtQgrs

**Comment by markwilliamfirth** [comment]
I saw these requirements (they come from another tech startup) and thought it a good idea to share them here:

**Overall Requirements**
Full contact details - full name, email address, phone number, address (if seller/valuation lead)
Full profile information, i.e. any and all additional information that the customer has provided/we have about them, such as their home selling/mortgage status, user-role etc
Product interaction and journey, i.e. CTAs clicked, pages visited etc
Historic touch-points with the customer via email, text and phone

**CS Requirements**
Ticket allocation for inbound customer support enquiries from both phone and email
Ticket categorisation based on keywords / conversation thread topic
Alerts for portfolio management catch-ups (every 2 weeks)
Alerts for time uncontacted
Automatic unpublishing of adverts based on a period of inactivity
FAQ build out based on frequent searches
Complaints procedure/policy document storing and look-back
Ticket analysis by time of day, frequency, first contact resolution
Analytics on average response times, individual productivity and SLA achievements
Reporting on daily new/solved tickets to gauge resource requirements
Logs and alerts for syndication errors
Tracking of progress along our photo/floorplan/description partner's funnel, e.g. appointment booked, appointment completed, media returned etc

**Sales Requirements**
Lead scoring/prioritisation
Automatic movement of leads along the sales flow based on certain actions/events (e.g. sales calls being made, sales emails being opened/clicked)
Tracking of number of leads being worked and conversion rates at each stage of the sales flow
Ticketing/recording of inbound sales enquiries via phone and email
Tracking/reporting on outbound sales contact made via phone and email
Automation of objection tracking
Alerts for hot leads
Setting SLAs
Alerts for upcoming SLA breaches
Tracked buyer search criteria from Rightmove/Zoopla/Settled
Legal/mortgage signups/conversions

**Marketing Requirements**
Email campaign automation
Email campaign performance tracking and reporting
Tracking of referral sources (ppc, PR articles etc)
Landing page performance
Persona build outs based on the stored data on each customer
Blog post/guide performance data

**Comment by nelsonic** [comment]
These "requirements" were _copy-pasted_ by "ghost" from _somewhere_ else:
![crm-reqs-copy-pasted](https://user-images.githubusercontent.com/194400/36117746-ae877230-1032-11e8-8028-7d11487962cc.png)
But did not make any effort to _attribute_ them to the original source.
Or _more importantly_ to _edit_ them to _remove_ the ***irrelevant*** points.

I cannot _stand_ it when people [_half-ass_](https://en.wiktionary.org/wiki/half-ass) their Job.
